import { getDay } from "date-fns";
import { toZonedTime, getTimezoneOffset } from "date-fns-tz";

/**
 * Returns a Smart Insight string comparing the two timezones.
 */
export function generateSmartInsight(
  sourceTz: string,
  targetTz: string,
  baseDate: Date = new Date(),
): string {
  try {
    const sourceOffsetMs = getTimezoneOffset(sourceTz, baseDate);
    const targetOffsetMs = getTimezoneOffset(targetTz, baseDate);

    const diffHours = (targetOffsetMs - sourceOffsetMs) / 3600000;

    const sourceZoned = toZonedTime(baseDate, sourceTz);
    const targetZoned = toZonedTime(baseDate, targetTz);

    const sDate = sourceZoned.getDate();
    const tDate = targetZoned.getDate();

    let dayShift = "";
    if (tDate > sDate) dayShift = " The target is already on the next day.";
    if (tDate < sDate) dayShift = " The target is still on the previous day.";

    if (diffHours === 0) {
      return `Both locations share the same time zone.${dayShift}`;
    }

    const direction = diffHours > 0 ? "ahead" : "behind";
    return `The destination is ${Math.abs(diffHours)} hours ${direction} of the origin.${dayShift}`;
  } catch {
    return "Time intelligence data could not be computed.";
  }
}

/**
 * Checks if a given hour (0-23) in a specific timezone is during typical business hours.
 */
export function isBusinessHours(dateInZone: Date): boolean {
  const hour = dateInZone.getHours();
  const day = getDay(dateInZone); // 0 = Sunday, 6 = Saturday
  const isWknd = day === 0 || day === 6;

  if (isWknd) return false;
  return hour >= 9 && hour < 17;
}

/**
 * Basic meeting score generation based on overlap of business hours.
 * Returns a score 0-100.
 */
export function calculateMeetingScore(
  sourceTz: string,
  targetTz: string,
  baseDate: Date = new Date(),
): number {
  try {
    const sourceZoned = toZonedTime(baseDate, sourceTz);
    const targetZoned = toZonedTime(baseDate, targetTz);

    const sHour = sourceZoned.getHours();
    const tHour = targetZoned.getHours();

    // Simplistic score based on how close both are to 9am-5pm
    const sScore =
      sHour >= 9 && sHour <= 17 ? 100 : sHour >= 7 && sHour <= 20 ? 50 : 0;
    const tScore =
      tHour >= 9 && tHour <= 17 ? 100 : tHour >= 7 && tHour <= 20 ? 50 : 0;

    return Math.floor((sScore + tScore) / 2);
  } catch {
    return 0;
  }
}

/**
 * Generates formatted text for copying/sharing.
 */
export function generateShareText(
  sourceName: string,
  sourceTime: string,
  targetName: string,
  targetTime: string,
): string {
  return `Time Conversion:\n${sourceName}: ${sourceTime}\n${targetName}: ${targetTime}\n\nGenerated by Aevion Labs`;
}
