import { readFile } from "fs/promises";
import path from "path";
import JSZip from "jszip";
import type { ProjectBundle } from "../types";
import { prefixPuckData } from "../puck/paths";

async function src(rel: string) {
  return readFile(path.join(process.cwd(), rel), "utf8");
}

function pageModule(slug: string) {
  const json = slug === "home" ? "../content/home.json" : `../../content/${slug}.json`;
  const config = slug === "home" ? "../puck.config" : "../../puck.config";
  return `import { Render } from "@puckeditor/core";
import { config } from "${config}";
import data from "${json}";

export default function Page() {
  return (
    <div className="factory-site">
      <Render config={config} data={data} />
    </div>
  );
}
`;
}

export async function buildExportZip(bundle: ProjectBundle) {
  const files: Record<string, string> = {};
  const css = await src("src/app/factory-site.css");
  const blocks = await src("src/features/website-factory/components/blocks.tsx");
  const config = (await src("src/features/website-factory/puck/config.tsx")).replace(
    "../components/blocks",
    "./components/blocks",
  );

  files["package.json"] = JSON.stringify(
    {
      name: bundle.project.slug,
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "16.2.0",
        react: "19.2.4",
        "react-dom": "19.2.4",
        "@puckeditor/core": "0.23.0",
      },
    },
    null,
    2,
  );
  files["next.config.mjs"] =
    "const nextConfig = { images: { unoptimized: true } };\nexport default nextConfig;\n";
  files["tsconfig.json"] = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        module: "esnext",
        moduleResolution: "bundler",
        jsx: "react-jsx",
        incremental: true,
        paths: { "@/*": ["./*"] },
      },
      include: ["**/*.ts", "**/*.tsx"],
    },
    null,
    2,
  );
  files["README.md"] = `# ${bundle.project.name}

Generated by Aevion Website Factory. This folder is a standalone Next.js site.

\`\`\`
npm install
npm run dev
\`\`\`

Live path on Aevion was \`/s/${bundle.project.slug}\`. This export has no dashboard, no editor chrome, and no Aevion credentials.
`;
  files[".env.example"] = "# No secrets required.\n";
  files["app/globals.css"] = `${css}

.factory-site {
  --wf-primary: ${bundle.project.theme.primary};
  --wf-secondary: ${bundle.project.theme.secondary};
  --wf-accent: ${bundle.project.theme.accent};
  --wf-bg: ${bundle.project.theme.background};
  --wf-fg: ${bundle.project.theme.foreground};
  --wf-heading: ${bundle.project.theme.headingFont};
  --wf-body: ${bundle.project.theme.bodyFont};
  --wf-radius: ${bundle.project.theme.radius};
}
`;
  files["app/layout.tsx"] = `import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: ${JSON.stringify(bundle.project.seoConfig.title || bundle.project.name)},
  description: ${JSON.stringify(bundle.project.seoConfig.description)},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="factory-site">{children}</div>
      </body>
    </html>
  );
}
`;
  files["components/blocks.tsx"] = blocks;
  files["puck.config.tsx"] = `${config}\nexport const config = factoryConfig;\n`;

  const home = bundle.pages.find((page) => page.slug === "home") ?? bundle.pages[0];
  if (!home) throw new Error("Website has no pages to export");

  for (const page of bundle.pages) {
    const data = prefixPuckData(page.publishedData ?? page.draftData, "");
    files[`content/${page.slug}.json`] = JSON.stringify(data, null, 2);
    if (page.slug === "home") {
      files["app/page.tsx"] = pageModule("home");
    } else {
      files[`app/${page.slug}/page.tsx`] = pageModule(page.slug);
    }
  }

  files["app/robots.ts"] = `import type { MetadataRoute } from "next";
export default function robots(): MetadataRoute.Robots {
  return { rules: { userAgent: "*", allow: "/" } };
}
`;

  const required = ["package.json", "app/layout.tsx", "app/page.tsx", "README.md", "puck.config.tsx"];
  const missing = required.filter((name) => !files[name]);
  if (missing.length) throw new Error(`Export incomplete: missing ${missing.join(", ")}`);

  const zip = new JSZip();
  const root = bundle.project.slug;
  for (const [name, contents] of Object.entries(files)) {
    zip.file(`${root}/${name}`, contents);
  }
  const buffer = await zip.generateAsync({ type: "nodebuffer" });
  console.info("[website-factory] export built", {
    slug: bundle.project.slug,
    files: Object.keys(files).length,
    bytes: buffer.length,
  });
  return { buffer, filename: `${bundle.project.slug}-website.zip`, files };
}
