export type TechFeed = {
  id: string;
  name: string;
  domain: string;
  country: string | null;
  language: string;
  category: string;
  rss_url: string | null;
  homepage_url: string | null;
  crawl_method: string;
  crawl_interval: number;
  priority: number;
  trust_score: number;
  max_requests_per_minute: number;
};

function feed(
  row: Omit<TechFeed, "language" | "crawl_method" | "crawl_interval"> & {
    crawl_interval?: number;
  },
): TechFeed {
  return {
    language: "en",
    crawl_method: "rss",
    crawl_interval: row.crawl_interval ?? 30,
    ...row,
  };
}

/**
 * Public, free RSS from tech publishers, engineer blogs, and discovery
 * aggregators. Google News rows are aggregators (not crawled by the registry
 * scraper) and are used by the RSS provider for wider coverage.
 */
export const TECH_FEEDS: TechFeed[] = [
  feed({
    id: "hacker-news",
    name: "Hacker News",
    domain: "news.ycombinator.com",
    country: "US",
    category: "Technology",
    rss_url: "https://hnrss.org/frontpage",
    homepage_url: "https://news.ycombinator.com/",
    priority: 100,
    trust_score: 0.9,
    max_requests_per_minute: 8,
  }),
  feed({
    id: "the-verge",
    name: "The Verge",
    domain: "theverge.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.theverge.com/rss/index.xml",
    homepage_url: "https://www.theverge.com/",
    priority: 96,
    trust_score: 0.88,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "ars-technica",
    name: "Ars Technica",
    domain: "arstechnica.com",
    country: "US",
    category: "Technology",
    rss_url: "https://feeds.arstechnica.com/arstechnica/index",
    homepage_url: "https://arstechnica.com/",
    priority: 95,
    trust_score: 0.9,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "techcrunch",
    name: "TechCrunch",
    domain: "techcrunch.com",
    country: "US",
    category: "Technology",
    rss_url: "https://techcrunch.com/feed/",
    homepage_url: "https://techcrunch.com/",
    priority: 92,
    trust_score: 0.82,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "wired",
    name: "Wired",
    domain: "wired.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.wired.com/feed/rss",
    homepage_url: "https://www.wired.com/",
    priority: 90,
    trust_score: 0.86,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "bbc-tech",
    name: "BBC Technology",
    domain: "bbc.co.uk",
    country: "GB",
    category: "Technology",
    rss_url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
    homepage_url: "https://www.bbc.co.uk/news/technology",
    priority: 88,
    trust_score: 0.9,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "the-register",
    name: "The Register",
    domain: "theregister.com",
    country: "GB",
    category: "Technology",
    rss_url: "https://www.theregister.com/headlines.atom",
    homepage_url: "https://www.theregister.com/",
    priority: 87,
    trust_score: 0.84,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "mit-tech-review",
    name: "MIT Technology Review",
    domain: "technologyreview.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.technologyreview.com/feed/",
    homepage_url: "https://www.technologyreview.com/",
    priority: 86,
    trust_score: 0.9,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "engadget",
    name: "Engadget",
    domain: "engadget.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.engadget.com/rss.xml",
    homepage_url: "https://www.engadget.com/",
    priority: 80,
    trust_score: 0.78,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "cnet",
    name: "CNET",
    domain: "cnet.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.cnet.com/rss/news/",
    homepage_url: "https://www.cnet.com/",
    priority: 78,
    trust_score: 0.76,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "venturebeat",
    name: "VentureBeat",
    domain: "venturebeat.com",
    country: "US",
    category: "Technology",
    rss_url: "https://venturebeat.com/feed/",
    homepage_url: "https://venturebeat.com/",
    priority: 77,
    trust_score: 0.74,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "zdnet",
    name: "ZDNET",
    domain: "zdnet.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.zdnet.com/news/rss.xml",
    homepage_url: "https://www.zdnet.com/",
    priority: 74,
    trust_score: 0.74,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "techradar",
    name: "TechRadar",
    domain: "techradar.com",
    country: "GB",
    category: "Technology",
    rss_url: "https://www.techradar.com/rss",
    homepage_url: "https://www.techradar.com/",
    priority: 70,
    trust_score: 0.7,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "techmeme",
    name: "Techmeme",
    domain: "techmeme.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.techmeme.com/feed.xml",
    homepage_url: "https://www.techmeme.com/",
    priority: 84,
    trust_score: 0.85,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "lobsters",
    name: "Lobsters",
    domain: "lobste.rs",
    country: "US",
    category: "Engineering",
    rss_url: "https://lobste.rs/rss",
    homepage_url: "https://lobste.rs/",
    priority: 82,
    trust_score: 0.88,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "dev-to",
    name: "DEV Community",
    domain: "dev.to",
    country: "US",
    category: "Engineering",
    rss_url: "https://dev.to/feed",
    homepage_url: "https://dev.to/",
    priority: 68,
    trust_score: 0.72,
    max_requests_per_minute: 6,
  }),
  feed({
    id: "github-blog",
    name: "GitHub Blog",
    domain: "github.blog",
    country: "US",
    category: "Engineering",
    rss_url: "https://github.blog/feed/",
    homepage_url: "https://github.blog/",
    priority: 83,
    trust_score: 0.9,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "stackoverflow-blog",
    name: "Stack Overflow Blog",
    domain: "stackoverflow.blog",
    country: "US",
    category: "Engineering",
    rss_url: "https://stackoverflow.blog/feed/",
    homepage_url: "https://stackoverflow.blog/",
    priority: 72,
    trust_score: 0.84,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "smashing-magazine",
    name: "Smashing Magazine",
    domain: "smashingmagazine.com",
    country: "DE",
    category: "Engineering",
    rss_url: "https://www.smashingmagazine.com/feed/",
    homepage_url: "https://www.smashingmagazine.com/",
    priority: 66,
    trust_score: 0.82,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "css-tricks",
    name: "CSS-Tricks",
    domain: "css-tricks.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://css-tricks.com/feed/",
    homepage_url: "https://css-tricks.com/",
    priority: 64,
    trust_score: 0.8,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "infoq",
    name: "InfoQ",
    domain: "infoq.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://feed.infoq.com/",
    homepage_url: "https://www.infoq.com/",
    priority: 71,
    trust_score: 0.82,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "thenewstack",
    name: "The New Stack",
    domain: "thenewstack.io",
    country: "US",
    category: "Engineering",
    rss_url: "https://thenewstack.io/feed/",
    homepage_url: "https://thenewstack.io/",
    priority: 73,
    trust_score: 0.8,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "changelog",
    name: "Changelog",
    domain: "changelog.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://changelog.com/feed",
    homepage_url: "https://changelog.com/",
    priority: 62,
    trust_score: 0.8,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "phoronix",
    name: "Phoronix",
    domain: "phoronix.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://www.phoronix.com/rss.php",
    homepage_url: "https://www.phoronix.com/",
    priority: 69,
    trust_score: 0.84,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "lwn",
    name: "LWN",
    domain: "lwn.net",
    country: "US",
    category: "Engineering",
    rss_url: "https://lwn.net/headlines/rss",
    homepage_url: "https://lwn.net/",
    priority: 75,
    trust_score: 0.9,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "hackaday",
    name: "Hackaday",
    domain: "hackaday.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://hackaday.com/feed/",
    homepage_url: "https://hackaday.com/",
    priority: 60,
    trust_score: 0.78,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "ieee-spectrum",
    name: "IEEE Spectrum",
    domain: "spectrum.ieee.org",
    country: "US",
    category: "Science",
    rss_url: "https://spectrum.ieee.org/feeds/feed.rss",
    homepage_url: "https://spectrum.ieee.org/",
    priority: 79,
    trust_score: 0.9,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "cloudflare-blog",
    name: "Cloudflare Blog",
    domain: "blog.cloudflare.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://blog.cloudflare.com/rss/",
    homepage_url: "https://blog.cloudflare.com/",
    priority: 76,
    trust_score: 0.88,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "google-developers",
    name: "Google Developers",
    domain: "developers.googleblog.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://developers.googleblog.com/feeds/posts/default",
    homepage_url: "https://developers.googleblog.com/",
    priority: 74,
    trust_score: 0.86,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "microsoft-devblogs",
    name: "Microsoft DevBlogs",
    domain: "devblogs.microsoft.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://devblogs.microsoft.com/feed/",
    homepage_url: "https://devblogs.microsoft.com/",
    priority: 70,
    trust_score: 0.84,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    domain: "huggingface.co",
    country: "US",
    category: "AI",
    rss_url: "https://huggingface.co/blog/feed.xml",
    homepage_url: "https://huggingface.co/blog",
    priority: 81,
    trust_score: 0.88,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "nvidia-blog",
    name: "NVIDIA Blog",
    domain: "blogs.nvidia.com",
    country: "US",
    category: "AI",
    rss_url: "https://blogs.nvidia.com/feed/",
    homepage_url: "https://blogs.nvidia.com/",
    priority: 72,
    trust_score: 0.8,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "9to5mac",
    name: "9to5Mac",
    domain: "9to5mac.com",
    country: "US",
    category: "Technology",
    rss_url: "https://9to5mac.com/feed/",
    homepage_url: "https://9to5mac.com/",
    priority: 67,
    trust_score: 0.74,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "9to5google",
    name: "9to5Google",
    domain: "9to5google.com",
    country: "US",
    category: "Technology",
    rss_url: "https://9to5google.com/feed/",
    homepage_url: "https://9to5google.com/",
    priority: 65,
    trust_score: 0.74,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "android-police",
    name: "Android Police",
    domain: "androidpolice.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.androidpolice.com/feed/",
    homepage_url: "https://www.androidpolice.com/",
    priority: 63,
    trust_score: 0.72,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "macrumors",
    name: "MacRumors",
    domain: "macrumors.com",
    country: "US",
    category: "Technology",
    rss_url: "https://feeds.macrumors.com/MacRumors-All",
    homepage_url: "https://www.macrumors.com/",
    priority: 66,
    trust_score: 0.76,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "hackernoon",
    name: "HackerNoon",
    domain: "hackernoon.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://hackernoon.com/feed",
    homepage_url: "https://hackernoon.com/",
    priority: 58,
    trust_score: 0.68,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "reddit-programming",
    name: "Reddit r/programming",
    domain: "reddit.com",
    country: "US",
    category: "Engineering",
    rss_url: "https://www.reddit.com/r/programming/.rss",
    homepage_url: "https://www.reddit.com/r/programming/",
    priority: 61,
    trust_score: 0.7,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "reddit-technology",
    name: "Reddit r/technology",
    domain: "reddit.com",
    country: "US",
    category: "Technology",
    rss_url: "https://www.reddit.com/r/technology/.rss",
    homepage_url: "https://www.reddit.com/r/technology/",
    priority: 59,
    trust_score: 0.68,
    max_requests_per_minute: 4,
  }),
  feed({
    id: "reddit-machinelearning",
    name: "Reddit r/MachineLearning",
    domain: "reddit.com",
    country: "US",
    category: "AI",
    rss_url: "https://www.reddit.com/r/MachineLearning/.rss",
    homepage_url: "https://www.reddit.com/r/MachineLearning/",
    priority: 60,
    trust_score: 0.72,
    max_requests_per_minute: 3,
  }),
  feed({
    id: "google-tech",
    name: "Google News Technology",
    domain: "news.google.com",
    country: "GB",
    category: "Technology",
    rss_url:
      "https://news.google.com/rss/headlines/section/topic/TECHNOLOGY?hl=en-GB&gl=GB&ceid=GB:en",
    homepage_url: "https://news.google.com/",
    crawl_interval: 20,
    priority: 85,
    trust_score: 0.6,
    max_requests_per_minute: 8,
  }),
  feed({
    id: "google-ai",
    name: "Google News AI",
    domain: "news.google.com",
    country: "GB",
    category: "AI",
    rss_url:
      "https://news.google.com/rss/search?q=%22artificial%20intelligence%22%20OR%20LLM%20OR%20ChatGPT&hl=en-GB&gl=GB&ceid=GB:en",
    homepage_url: "https://news.google.com/",
    crawl_interval: 20,
    priority: 84,
    trust_score: 0.55,
    max_requests_per_minute: 8,
  }),
  feed({
    id: "google-security",
    name: "Google News Cybersecurity",
    domain: "news.google.com",
    country: "GB",
    category: "Technology",
    rss_url:
      "https://news.google.com/rss/search?q=cybersecurity%20OR%20ransomware%20OR%20CVE&hl=en-GB&gl=GB&ceid=GB:en",
    homepage_url: "https://news.google.com/",
    crawl_interval: 20,
    priority: 83,
    trust_score: 0.55,
    max_requests_per_minute: 8,
  }),
  feed({
    id: "google-opensource",
    name: "Google News Open Source",
    domain: "news.google.com",
    country: "GB",
    category: "Engineering",
    rss_url:
      "https://news.google.com/rss/search?q=%22open%20source%22%20OR%20github%20OR%20linux&hl=en-GB&gl=GB&ceid=GB:en",
    homepage_url: "https://news.google.com/",
    crawl_interval: 20,
    priority: 80,
    trust_score: 0.55,
    max_requests_per_minute: 8,
  }),
];
