export type ComponentMeta = {
  purpose: string;
  placement: string;
  variants: string[];
  constraints: string;
};

export const COMPONENT_META: Record<string, ComponentMeta> = {
  AnnouncementBar: {
    purpose: "Short notice above the header",
    placement: "First on every page",
    variants: ["text"],
    constraints: "One line. No claims not in the business record.",
  },
  Navbar: {
    purpose: "Site chrome and primary CTA",
    placement: "Global header",
    variants: ["sticky", "static"],
    constraints: "Links must point at real pages.",
  },
  Hero: {
    purpose: "Opening statement",
    placement: "Home, after nav",
    variants: ["with image", "type only"],
    constraints: "Headline from tagline or name.",
  },
  SplitHero: {
    purpose: "Split text and media hero",
    placement: "Home or landing",
    variants: ["image right"],
    constraints: "Use real business imagery.",
  },
  VideoHero: {
    purpose: "Hero with video media",
    placement: "Home when a reel exists",
    variants: ["youtube", "mp4"],
    constraints: "Video URL must be public.",
  },
  ContactForm: {
    purpose: "Mailto contact form",
    placement: "Contact page",
    variants: ["simple"],
    constraints: "No server-side message storage.",
  },
  FooterColumns: {
    purpose: "Multi-column footer",
    placement: "Site chrome",
    variants: ["3 columns"],
    constraints: "Links must resolve to real pages.",
  },
  TrustIndicators: {
    purpose: "Proof strip",
    placement: "Under hero",
    variants: ["labels"],
    constraints: "Only supplied trust lines.",
  },
  Services: {
    purpose: "Offer list",
    placement: "Home or services page",
    variants: ["grid"],
    constraints: "Each item is a business service.",
  },
  AboutSection: {
    purpose: "Who the firm is",
    placement: "Home or about",
    variants: ["with image"],
    constraints: "Body from the business description.",
  },
  Testimonials: {
    purpose: "Quoted reviews",
    placement: "After work or services",
    variants: ["quotes"],
    constraints: "Do not invent reviewers.",
  },
  Gallery: {
    purpose: "Photographs of work",
    placement: "Projects or home",
    variants: ["grid"],
    constraints: "Use imported or uploaded assets only.",
  },
  Process: {
    purpose: "How the work proceeds",
    placement: "Home or about",
    variants: ["steps"],
    constraints: "Template defaults unless the operator edits.",
  },
  FAQ: {
    purpose: "Direct answers",
    placement: "Before contact",
    variants: ["accordion"],
    constraints: "No invented certifications.",
  },
  CTA: {
    purpose: "Convert",
    placement: "Before footer",
    variants: ["solid"],
    constraints: "Label from primary CTA.",
  },
  ContactSection: {
    purpose: "How to reach the firm",
    placement: "Contact page",
    variants: ["details"],
    constraints: "Phone, email, address from the record.",
  },
  Footer: {
    purpose: "Closing chrome",
    placement: "Last on every page",
    variants: ["compact"],
    constraints: "Name and contact only.",
  },
  Stats: {
    purpose: "Numeric proof already in the record",
    placement: "After about",
    variants: ["row"],
    constraints: "Do not invent figures.",
  },
  Pricing: {
    purpose: "Named offers with optional price",
    placement: "Services page",
    variants: ["cards"],
    constraints: "Price only if supplied.",
  },
  BeforeAfter: {
    purpose: "Two photographs of a job",
    placement: "Projects",
    variants: ["pair"],
    constraints: "Needs two authorized images.",
  },
  LogoCloud: {
    purpose: "Marks the operator has rights to show",
    placement: "After trust",
    variants: ["row"],
    constraints: "No fabricated client logos.",
  },
  MapEmbed: {
    purpose: "Location",
    placement: "Contact",
    variants: ["openstreetmap link"],
    constraints: "Address from the record. No tracking pixels.",
  },
  SocialLinks: {
    purpose: "Profiles",
    placement: "Footer or contact",
    variants: ["text links"],
    constraints: "Only supplied profile URLs.",
  },
  Breadcrumbs: {
    purpose: "Orientation",
    placement: "Inner pages",
    variants: ["text"],
    constraints: "Home plus current page.",
  },
  BlogGrid: {
    purpose: "Articles if they exist",
    placement: "Blog page",
    variants: ["list"],
    constraints: "Do not invent posts.",
  },
  Heading: {
    purpose: "Section title",
    placement: "Anywhere",
    variants: ["h1", "h2", "h3", "h4", "align", "size"],
    constraints: "Keep heading order sensible.",
  },
  TextBlock: {
    purpose: "Copy",
    placement: "Anywhere",
    variants: ["richtext", "align"],
    constraints: "Operator-authored or imported text only.",
  },
  ImageBlock: {
    purpose: "Media",
    placement: "Anywhere",
    variants: ["width", "height", "object-fit", "radius"],
    constraints: "Use imported or uploaded assets only.",
  },
  ButtonBlock: {
    purpose: "CTA control",
    placement: "Anywhere",
    variants: ["solid", "ghost", "size", "full width"],
    constraints: "Href must be a real route or URL.",
  },
  Section: {
    purpose: "Full-bleed layout frame",
    placement: "Page structure",
    variants: ["padding", "background"],
    constraints: "Nest content via slot.",
  },
  Container: {
    purpose: "Centered max-width frame",
    placement: "Inside sections",
    variants: ["max width"],
    constraints: "Nest content via slot.",
  },
  Flex: {
    purpose: "Flexbox layout",
    placement: "Structure",
    variants: ["row", "column", "gap", "align"],
    constraints: "Nest content via slot.",
  },
  Grid: {
    purpose: "CSS grid layout",
    placement: "Structure",
    variants: ["2–6 columns", "gap"],
    constraints: "Nest content via slot.",
  },
  Box: {
    purpose: "Styled container",
    placement: "Anywhere",
    variants: ["padding", "radius", "shadow"],
    constraints: "Nest content via slot.",
  },
  Columns3: {
    purpose: "Three column layout",
    placement: "Structure",
    variants: ["gap"],
    constraints: "Three slots.",
  },
  VideoBlock: {
    purpose: "Embedded video",
    placement: "Anywhere",
    variants: ["youtube", "mp4"],
    constraints: "Only authorized media URLs.",
  },
  IconList: {
    purpose: "Feature bullets",
    placement: "Home or services",
    variants: ["list"],
    constraints: "No invented claims.",
  },
  MobileNavbar: {
    purpose: "Compact mobile navigation",
    placement: "Global header on small screens",
    variants: ["details menu"],
    constraints: "Links must match real pages.",
  },
  MinimalHero: {
    purpose: "Type-first opening statement",
    placement: "Landing or about",
    variants: ["centered"],
    constraints: "Headline from tagline or name.",
  },
  ImageText: {
    purpose: "Image beside copy",
    placement: "About or feature sections",
    variants: ["image left", "image right"],
    constraints: "Use real business photography.",
  },
  FeatureGrid: {
    purpose: "Feature or benefit cards",
    placement: "Home mid-page",
    variants: ["3 column"],
    constraints: "Keep titles short.",
  },
  ServiceCard: {
    purpose: "Single service card",
    placement: "Inside services layouts",
    variants: ["with image"],
    constraints: "Map to a business service.",
  },
  Projects: {
    purpose: "Project grid",
    placement: "Work page",
    variants: ["cards"],
    constraints: "Do not invent case studies.",
  },
  ProjectCard: {
    purpose: "Single project card",
    placement: "Inside Projects",
    variants: ["image"],
    constraints: "Use real project names.",
  },
  TeamMember: {
    purpose: "Team member card",
    placement: "Team section",
    variants: ["photo"],
    constraints: "Only listed people.",
  },
  Certifications: {
    purpose: "Certification list",
    placement: "About or trust strip",
    variants: ["list"],
    constraints: "Only supplied certifications.",
  },
  Awards: {
    purpose: "Awards list",
    placement: "About or trust strip",
    variants: ["list"],
    constraints: "Only supplied awards.",
  },
  BookingCTA: {
    purpose: "Booking call to action",
    placement: "Near contact",
    variants: ["solid"],
    constraints: "Href must be a real booking or contact link.",
  },
  QuoteForm: {
    purpose: "Mailto quote request",
    placement: "Contact page",
    variants: ["simple"],
    constraints: "No server-side storage.",
  },
  Newsletter: {
    purpose: "Email capture prompt",
    placement: "Footer or blog",
    variants: ["inline"],
    constraints: "Honest about where email goes.",
  },
  TeamSection: {
    purpose: "Team grid",
    placement: "About or team page",
    variants: ["cards"],
    constraints: "Only listed people.",
  },
  AreasServed: {
    purpose: "Service area list",
    placement: "Home or contact",
    variants: ["list"],
    constraints: "Use real areas.",
  },
  PageHero: {
    purpose: "Interior page header",
    placement: "Top of secondary pages",
    variants: ["type only"],
    constraints: "Match page title.",
  },
  Spacer: {
    purpose: "Vertical spacing",
    placement: "Between sections",
    variants: ["height"],
    constraints: "Prefer theme spacing.",
  },
  Divider: {
    purpose: "Horizontal rule",
    placement: "Between sections",
    variants: ["line"],
    constraints: "Keep subtle.",
  },
  TwoColumn: {
    purpose: "Two column layout",
    placement: "Content sections",
    variants: ["equal"],
    constraints: "Balance content weight.",
  },
};
